# AUTOGENERATED! DO NOT EDIT! File to edit: .ipynb_checkpoints/00_core-checkpoint.ipynb (unless otherwise specified).

__all__ = ['say_hello', 'say_hello']

# Cell
def say_hello(to):
    "Say hello to somebody"
    return f'Hello {to}!'

# Cell
def say_hello(to):
    "Say hello to somebody"
    return f'Hello {to}!'